### ISSUE TITLE
Cake 5 Update - getConnection has been removed and the new getPdo is protected

### ISSUE THREAD

**Issue by samuelgfeller** [selective-php/test-traits#10]
In the new Cake 5 update, they [removed](https://github.com/cakephp/cakephp/pull/16351#discussion_r815378875) the access to the `PDO` connection instance. Replacement is `Driver::exec` but that changes quite some things in `DatabaseConnectionTestTrait` and `DatabaseSchemaTestTrait.php`.
 
Discussion on the topic: https://discourse.cakephp.org/t/how-to-get-pdo-connection-in-cake-5/11583

**Comment by odan** [comment]
For Cake v5 you can use Reflection to get the PDO instance:

```php
PDO::class => function (ContainerInterface $container) {
    $driver = $container->get(Connection::class)->getDriver();

    $class = new ReflectionClass($driver);
    $method = $class->getMethod('getPdo');
    $method->setAccessible(true);

    return $method->invoke($driver);
},
```

So no change is needed within the DatabaseConnectionTestTrait.

**Comment by samuelgfeller** [comment]
Oh okay, well that fixes everything. So there is no need to change the test traits, yes, and that keeps the traits from being query builder dependent! Awesome.

**Comment by jimgwhit** [comment]
@odan where would this code be placed to use it?

```
PDO::class => function (ContainerInterface $container) {
    $driver = $container->get(Connection::class)->getDriver();

    $class = new ReflectionClass($driver);
    $method = $class->getMethod('getPdo');
    $method->setAccessible(true);

    return $method->invoke($driver);
},
```

And how to call it since it's not a direct method or function?

Can you give an example of usage?
