### ISSUE TITLE
Fixture Trait

### ISSUE THREAD

**Issue by samuelgfeller** [selective-php/test-traits#14]
Hi,

The `FixtureTestTrait` is one of my most used test traits, and I think it could be a good fit for this library. 

What I'm suggesting is renaming the `insertFixture` function from the `DatabaseSchemaTestTrait.php` to `insertFixtureRow` 
and then creating a new trait `FixtureTestTrait` which contains the `insertFixture` function.

It accepts the fixture instance and an array of attributes that override the default values from the records array of the fixture class. 
That way, each test function can independently insert fixtures with relevant values to the test case. Multiple records can be inserted when `$attributes` is an array of attribute arrays.  
It returns the inserted values so that the test function can work with them. 

```php
<?php

use App\Test\Fixture\FixtureInterface;
use Selective\TestTrait\Traits\DatabaseTestTrait;

trait FixtureTestTrait
{
    use DatabaseTestTrait;

    /**
     * Inserts fixtures with given attributes or sets of attributes and returns rows with id.
     *
     * @param FixtureInterface $fixture the fixture instance
     * @param array $attributes attributes to override in the fixture
     * Format: ['field_name' => 'expected_value', 'other_field_name' => 'other expected value', ] -> one insert
     * alternatively [['field_name' => 'expected_value'], ['field_name' => 'expected_value'], ] -> two insets
     * @return array inserted row values
     */
    protected function insertFixture(FixtureInterface $fixture, array $attributes = []): array
    {
        $multipleRows = true;

        // Check if attributes is an array with multiple sets of attributes or only one array of attributes
        if (count($attributes) === count($attributes, COUNT_RECURSIVE)) {
            // Put $attributes in an additional array
            $attributes = [$attributes];
            $multipleRows = false;
        }

        $insertedRows = [];
        foreach ($attributes as $attributesForOneRow) {
            // Get row with given attributes
            $row = $this->getFixtureRowWithCustomAttributes($attributesForOneRow, $fixture);
            // Insert fixture and get id
            $row['id'] = (int)$this->insertFixtureRow($fixture->getTable(), $row);
            $insertedRows[] = $row;
        }

        // If only one row was inserted, return the row values
        if ($multipleRows === false) {
            return $insertedRows[0];
        }

        // Return array of inserted row values
        return $insertedRows;
    }

    /**
     * Returns fixtures with given attributes and returns row values with id.
     *
     * @param array $attributes
     * @param FixtureInterface $fixture
     *
     * @return array
     */
    private function getFixtureRowWithCustomAttributes(
        array $attributes,
        FixtureInterface $fixture,
    ): array {
        $row = $fixture->getRecords()[0];

        // Unset id to prevent duplicate entries when id is not provided in the attributes and multiple inserts are made
        unset($row['id']);

        // Add given attributes to row
        foreach ($attributes as $colum => $value) {
            // Set value to given attribute value
            $row[$colum] = $value;
        }

        return $row;
    }
}
``` 

Let me know if I can make a pull request with this trait. 

Note that to satisfy phpstan lvl 8 inspection, the fixture parameter is a `FixtureInterface` and each fixture must implement the functions `getTable` and `getRecords` because unfortunately php doesn't allow interfaces to set required attributes, only functions can be declared.

**Comment by samuelgfeller** [comment]
If you're not down to add `FixtureTestTrait` into your library, can I at least change the `insertFixture` method name to `insertFixtureRow`? 
I can have the `FixtureTestTrait` locally there is no problem but I'd like to use the `insertFixture` name as I find it more suitable in my `FixtureTestTrait` (which inserts fixture objects) than in the `DatabaseSchemaTestTrait` which just inserts a row of data.

**Comment by odan** [comment]
Hi! Thanks for your detailed suggestion and the work you've put into it. I aim to keep the core functionality as lean and focused as possible, and while your proposed trait would be useful in certain contexts, it introduces a level of specificity that may not align with the broader use cases I've targeting.

However, you might consider **forking** this package to implement and maintain this feature in your version.

**Comment by samuelgfeller** [comment]
I made a clone of this package with a trait to insert fixtures with specific test-case-relevant attributes [samuelgfeller/test-traits](https://github.com/samuelgfeller/test-traits).  
[Here](https://github.com/samuelgfeller/test-traits?tab=readme-ov-file#fixturetesttrait) is how to use it.
