### ISSUE TITLE
DatabaseTestTrait: Unknown system variable 'information_schema_stats_expiry'

### ISSUE THREAD

**Issue by samuelgfeller** [selective-php/test-traits#3]
I get the following error 
```
PDOException : SQLSTATE[HY000]: General error: 1193 Unknown system variable 'information_schema_stats_expiry'
```
In the `unsetStatsExpiry()` function of `DatabaseTestTrait` `SET information_schema_stats_expiry=0;` is called but my database doesn't seem to have this system variable. 
When I execute `SHOW VARIABLES LIKE 'information_schema_stats_expiry';` there are no results. 

My XAMPP Version is v3.2.4 and `SHOW VARIABLES LIKE 'version';` returns `10.4.11-MariaDB`. I'll try to update mariaDB to the newest version and see if that fixes it.

**Comment by odan** [comment]
This is a MySQL 8+ specific variable: `information_schema_stats_expiry`

https://mariadb.com/kb/en/system-variable-differences-between-mariadb-103-and-mysql-80/

We should add a database to this method.

`SHOW VARIABLES LIKE "version_comment";`

Then you should see something like `MariaDB` Server OR `MySQL`

**Comment by odan** [comment]
It should now work for MariaDB as well.

**Comment by samuelgfeller** [comment]
Oh so it's a variable that exists only on `MySQL` and not `MariaDB`. I didn't get that right away. 

Thanks for the update!
