### ISSUE TITLE
DatabaseTestTrait::findTableRowById() has fixed column name for id.

### ISSUE THREAD

**Issue by DigiLive** [selective-php/test-traits#8]
The query of method `DatabaseTestTrait::findTableRowById()` has fixed value `id` as a name for the record identifier (assumed Primary Key).
However, the name such a column can freely be chosen by developers.

Can you make fixed value `id` a parameter of this function or trait property?
E.g.
```php
protected function findTableRowById(string $table, int $id, string $column = 'id'): array
findTableRowById('myTable', 1, 'myId');
```

**Comment by odan** [comment]
Yes, this should be no problem. Can you create a PR please?

**Comment by DigiLive** [comment]
> Can you create a PR please?

Yes, no problem.

I was thinking...
There several ways to handle a 'variable' name of the column, designated as id.
1. Add a parameter to several methods, like initially requested. (Versatile, but more coding required when the name isn't the default name)
2. If the current `id` column is meant to be the primary key, get the primary key column name by query first. (The query might not work on different servers, e.g. for mySQL/MariaDB  `SHOW KEYS FROM table WHERE Key_name = 'PRIMARY'`
3. Use a setter to store the name of the column, designated as id as a trait property. (Not quite good when needing to query different tables)

Please give me your 5 cents and I will create a PR.

**Comment by odan** [comment]
Actually I want to keep theses trait methods as simple as possible. The method name `findTableRowById` also implies that the primary key name is always just "id". After thinking about it, I would recommend (for such an special use case) that you implement your own helper trait methods for your specific database naming convention.

**Comment by DigiLive** [comment]
Fair enough, I'll create my own trait.

But imho fixing the primary key to field 'id' is the special use case.
The primary key can be any table field that uniquely identifies a record.

Thanks anyway, I've learned much from you in my explorations in the world of php.

**Comment by LosD** [comment]
> The method name findTableRowById also implies that the primary key name is always just "id". After thinking about it, I would recommend (for such an special use case) that you implement your own helper trait methods for your specific database naming convention.

@odan Sorry, but this is a bit of a silly argument. The DB trait is pretty useless as-is, unless you're using a very specific structure. There's nothing "special use case" about not using "id" as the primary key, and I would guess this collection of traits is supposed to be general purpose?

... "tablename_id" seems to be the most used, e.g. that is what is used in both the [mssql](https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/msarticles-transact-sql) and mysql/mariadb (see below) system tables (Postgres seems to use "oid" instead, so it is definitely not universal).
![image](https://github.com/selective-php/test-traits/assets/1282832/45dbc76a-dad5-4f82-a846-37e820d056ad)

**Comment by odan** [comment]
@LosD It's not useless :-) As mentioned earlier, if you have a different naming convention for primary keys, you can use a custom Trait for your environment.

**Comment by LosD** [comment]
@odan As a general db testing solution? I'm afraid so. While it is unavoidable that testing affects internal design to some extend (often with good reason), this can only specifically be used for testing a rather rigid database schema layout which is far from universal.

Fair enough if it isn't meant as such.
